language: python

python:
    - "3.4"
    - "pypy3"

env:
    - DB="sqlite://"
    - DB="postgresql+psycopg2://postgres@127.0.0.1/evesrp_test"
    - DB="postgresql+pg8000://postgres@127.0.0.1/evesrp_test"
    - DB="mysql+pymysql://root@127.0.0.1/evesrp_test"
    - DB="mysql+cymysql://root@127.0.0.1/evesrp_test"

matrix:
    include:
        - python: "3.3"
          env: DB="sqlite://"
    allow_failures:
        - python: "pypy3"
    fast_finish: true

install: make build-deps

before_script:
    - psql -c 'CREATE DATABASE evesrp_test;' -U postgres
    - mysql -e 'CREATE DATABASE evesrp_test;'
    - make all

script: make test

before_deploy: make all

deploy:
    - provider: pypi
      user: paxswill
      password:
          secure: Jl8/AGFMC0TZi4yUDj2DIf8ieNsMFOBT1R6FVyhSbBVm6jIFzOuy58tt2VZibkwFHVaacFeyE7odcPU9nzPCqE2XtPo+6f57I3spbDnI08iJQHd2DeByNLG49hZPnuvNNauRxPr4RhnNaV3IXVO9xmPB0v/+uykdfGERyu6tPms=
      on:
          branch: release
      skip_cleanup: true
    - provider: github
      api_key:
          secure: dwFUw1S2wfCRMW+iBv9/7VaBgmL+XaTciWQb31bzDJpJpX+3XB5JYJVRs2T/59OHKxYWZ7OsNo4RrHdlLaFO4f4lVcv8e5ynSWtPtPi5o8gKq6oCNJpYeUdlF1uSvbTbgETnA6srJ25lk30A02xqlNf2DAAENcKcwqREQuHXesM=
      on:
          branch: release
      skip_cleanup: true
      file: dist/EVE-SRP-*.tar.gz
